### ISSUE TITLE
docs: add CONTRIBUTING.md

### ISSUE THREAD

**Issue by BBarisKilic** [BBarisKilic/Animated-SVG#10]
For #8 

Add CONTRIBUTING.md:

- [ ] add CONTRIBUTING.md

**Comment by the-amazing-atharva** [comment]
Hi I would like to contribute to the this issue!

**Comment by BBarisKilic** [comment]
> Hi I would like to contribute to the this issue!

Hi! Thank you for your offer, but I already have a template for this. So I would prefer to modify it and use it.

**Comment by the-amazing-atharva** [comment]
No worries!
